ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "device" TEXT NOT NULL DEFAULT 'all';
ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "mobileImageUrl" TEXT;
ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "desktopImageUrl" TEXT;
ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "mobileHtml" TEXT;
ALTER TABLE "Ad" ADD COLUMN IF NOT EXISTS "desktopHtml" TEXT;

